server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modern_pos_system
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always