package com.residuesolution.pos.dto;

import com.residuesolution.pos.enums.InventoryChangeType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class InventoryLog {
    private Integer id;
    private Integer productId;
    private Integer changedBy;        // User ID who made the change
    private InventoryChangeType changeType;  // ADD, REMOVE, ADJUST, SALE_RETURN, etc.
    private Integer quantity;         // Quantity changed (positive or negative)
    private String reason;           // Reason for the change
    private Integer previousStock;   // Stock before change
    private Integer newStock;        // Stock after change
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    // Additional fields for comprehensive tracking
    private String notes;
    private String referenceId;      // Reference to order, return, or adjustment ID
    private Boolean isSystemGenerated; // True if generated by system (e.g., sales), false if manual

    public void info(String s, Integer productId, Integer quantity) {
    }

    public void info(String s, Integer productId, Integer previousStock, Integer newQuantity) {
    }
}